apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: migupele/java_school_online_store_api:master
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env: 
        - name: DATABASE_HOSTNAME
          valueFrom: 
            configMapKeyRef:
              name: postgres-config
              key: postgres-url
        - name: MAIL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mail-secret
              key: mail-username
        - name: MAIL_PASSWORD
          valueFrom:  
            secretKeyRef:
              name: mail-secret
              key: mail-password
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - protocol: 
      name: http-traffic
      port: 8081
      targetPort: 8081
      nodePort: 30100
  selector:
    app: api
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: 
  name: spring-prometheus-service-monitor
spec:
  selector: 
    matchLabels:
      app: spring-prometheus
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"