apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        env: 
        - name: apiUrl
          value: "8081" 
        image: migupele/java_school_online_store_frontend:latest
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - protocol: TCP
      nodePort: 30400
      port: 4200
      targetPort: 4200
  selector:
    app: frontend
  type: LoadBalancer