apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: online_store
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-claim
      restartPolicy: Always
      volumes:
        - name: postgres-claim
          persistentVolumeClaim:
            claimName: postgres-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-claim
  name: postgres-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - protocol: TCP
      nodePort: 30500
      port: 5432
      targetPort: 5432
  selector:
    app: postgres
  type: NodePort