apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        env:
        - name: SONARQUBE_JDBC_HOSTNAME
          value: postgres
        - name: SONARQUBE_JDBC_USERNAME
          value: postgres
        - name: SONARQUBE_JDBC_PASSWORD
          value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30600
  type: LoadBalancer