apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: admin@admin.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: admin
        volumeMounts:
            - mountPath: /var/lib/pgadmin
              name: pgadmin-claim
      restartPolicy: Always
      volumes:
        - name: pgadmin-claim
          persistentVolumeClaim:
            claimName: pgadmin-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pgadmin-claim
  name: pgadmin-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 80
      nodePort: 30300
  selector:
    app: pgadmin
  type: LoadBalancer